stages:
  - update
  - security-analysis
  - security-gate
include:
  - component: $CI_SERVER_FQDN/fis-asp/intern/technical-services/team-8/gitlab/asp8-ci-cd-templates/template-branch-sync@v1.11.5
    inputs:
      remote-path: "fis-asp/intern/technical-services/team-8/hypervisor/suse-virtualization/vsphere-2-harvester.git"
      runner-tags: ["asp-svp-mgmt.asp.aspint.de"]
      push-enable: true
      chown-enable: false
      repo-base: "/root/vsphere-2-harvester"	
      use-job-token: false
      alt-token: "$PUSH_TOKEN"
      auto-commit-enable: true
      prune-missing-enable: true
  - component: $CI_SERVER_FQDN/fis-asp/intern/technical-services/team-8/gitlab/asp8-ci-cd-templates/template-secret-scan@v1.11.5
